// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnums:
== Reset Considerations

`mepa_reset()` really is an initialization requirement for all our PHYs, and furthermore
the exact sequence is crucial in order to get all workarounds applied.

VSC/Tesla and Indy:

`mepa_reset()` has to be called 3 times.

There are 3 Reset Parameters in total.
1. `MEPA_RESET_POINT_PRE`
2. `MEPA_RESET_POINT_DEFAULT`
3. `MEPA_RESET_POINT_POST`

The "Normal" suequence should be iterating through the ports and initializing in
a particular manner and the order should be:

For any Port configured in PHY: mepa_reset (`MEPA_RESET_POINT_PRE`) // Reset can be called for any ports from the application. No Reset Considerations that should be called only for Port 0 of phy. It is phy specific and Internal phy API takes care of it.

For any Port configured in PHY: mepa_reset (`MEPA_RESET_POINT_DEFAULT`)

For any Port configured in PHY: mepa_reset (`MEPA_RESET_POINT_POST`) // Reset can be called for any ports from the application. No Reset Considerations that it should be called only for Port 3 of phy. It is phy specific and Internal phy API takes care of it.

=== API References
`mepa_reset()`
