# Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: Pod
metadata:
  name: ungsw-mesa-build-env
spec:
  containers:
    - name: pod-mepa-base
      image: 'artifacts-aws.devops.microchip.com:7996/ung/mepa/mepa-pod-base:latest@sha256:7af0b555f96980e00c8bbaaf8f30c1f55039e716b8fc3894cebf458b92d83b65'
      imagePullPolicy: IfNotPresent
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 4Gi

